### ISSUE TITLE
AttributeError: type object 'FileHandler' has no attribute 'read_mask'

### ISSUE THREAD

**Issue by tigerk** [okunator/cellseg_models.pytorch#51]
when i run [lizard_nuclei_segmentation_cellpose.ipynb].(https://github.com/okunator/cellseg_models.pytorch/blob/main/examples/lizard_nuclei_segmentation_cellpose.ipynb)

Found all folds. Skip downloading.
Splitting the files into train, valid, and test sets.
Patch the data... This will take a while...
Extracting train patches to folders..: 100%|██████████| 70/70 [15:35<00:00, 13.36s/it, # of extracted tiles 2451]
Extracting valid patches to folders..: 100%|██████████| 70/70 [17:03<00:00, 14.62s/it, # of extracted tiles 2748]
Extracting test patches to folders..: 100%|██████████| 98/98 [13:35<00:00,  8.32s/it, # of extracted tiles 2627]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_7576\871233218.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kimhw/Downloads/~/AppData/Local/Temp/ipykernel_7576/871233218.py) in 
     10 im2 = csmp.utils.FileHandler.read_img(imgs[50])
     11 im3 = csmp.utils.FileHandler.read_img(imgs[300])
---> 12 mask1 = csmp.utils.FileHandler.read_mask(masks[0], return_all=True)
     13 mask2 = csmp.utils.FileHandler.read_mask(masks[50], return_all=True)
     14 mask3 = csmp.utils.FileHandler.read_mask(masks[300], return_all=True)

AttributeError: type object 'FileHandler' has no attribute 'read_mask'

how do i fix this issue?

**Comment by okunator** [comment]
Hi,

The method `read_mask` has changed to `read_mat` in the latest release. I will fix the notebooks in my next release but in the mean time u can do that yourself directly in the notebook.
