### ISSUE TITLE
Data preparation issue

### ISSUE THREAD

**Issue by sunyoung0509** [okunator/cellseg_models.pytorch#56]
I had the same issue with the person who had issued you with the title 'Data preparation issue' There was an error saying "AttributeError: type object 'FileHandler' has no attribute 'write_mask'". But after upgrading the module cellseg_models_pytorch I didn't get the same error. but after running the code in the first cell I get a blank file in train/images & train/labels.

**Comment by okunator** [comment]
Try removing those folders and trying again.

**Comment by sunyoung0509** [comment]
If I run the code after removing all the folders, then I get the error saying "AttributeError: type object 'FileHandler' has no attribute 'write_mask'"

**Comment by okunator** [comment]
I think you still might have an outdated version of the package. In the newest version 0.1.20 the `write_mask` has been renamed to `write_mat` which is prbly the origin of the error. But if there is an actual bug in the newest version, it would be helpful if you pasted the error stack trace here so I could locate it and fix it.

**Comment by sunyoung0509** [comment]
I used the code "pip install cellseg-models-pytorch[all]" to download the module. But the newest version is 0.1.15.

Could not find a version that satisfies the requirement cellseg-models-pytorch==0.1.20 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15)

**Comment by sunyoung0509** [comment]
please... Help me!!

**Comment by okunator** [comment]
This might be related to your python version. The version of scipy and numpy was bumped up after 0.1.15 and the scipy version requires python 3.8+. If your python version is less than 3.8, try to upgrade your python or create an environment with python version greater or equal to 3.8
