### ISSUE TITLE
pannuke_datamodule.py is different between your installed package and github code.  

### ISSUE THREAD

**Issue by yellofi** [okunator/cellseg_models.pytorch#63]
This is the code in cellseg_models_pytorch.datamodules.pannuke_datamodule.py in the python packages directory

![image](https://github.com/okunator/cellseg_models.pytorch/assets/47804036/b92c8b6e-d7db-44b7-ade3-a65c75c7df53)

This is the code in cellseg_models_pytorch.datamodules.pannuke_datamodule.py of your github code.
![image](https://github.com/okunator/cellseg_models.pytorch/assets/47804036/85b83e87-a8f9-43ab-abb3-9a0c1425a40a)

I installed your awesome package, cellseg_models_pytorch and am checking its running via 'pannuke_nuclei_segmentation_cellpose.ipynb'.

There was such a issue above. Could you check your examples with jupyter notebook do work?

**Comment by okunator** [comment]
Hi,

thanks for the heads up. I'll check the issue.

**Comment by yellofi** [comment]
I think your example of the cellpose with jupyter notebook had run using module of your github code..
I fixed errors on the jupyter notebook example since I modify the code of your package referring your in-github code.

I think the issue is from the change of order of 'phase' and 'fold' in fold_split.

**Comment by okunator** [comment]
This issue is fixed with the latest release
