### ISSUE TITLE
How can I solve this error

### ISSUE THREAD

**Issue by arjunreddy25** [okunator/cellseg_models.pytorch#65]
--> [112](https://file+.vscode-resource.vscode-cdn.net/d%3A/hovernet/~/AppData/Local/Programs/Python/Python310/lib/urllib/parse.py:112)     return tuple(x.decode(encoding, errors) if x else '' for x in args)

AttributeError: 'WindowsPath' object has no attribute 'decode'

**Comment by okunator** [comment]
Hi, Can you send the full error trace here and the code that produced that error. To me that looks to be related to some of the third-party dependencies of this library.
