### ISSUE TITLE
Model diagram

### ISSUE THREAD

**Issue by vadori** [okunator/cellseg_models.pytorch#66]
Hi!  

Thanks for sharing! Is there a source available where I can find the architecture diagram, such as for the CellPose model with a UNI encoder?

**Comment by okunator** [comment]
Hi, can you specify what do you mean by the architecture diagram? The encoders in this library are imported from the `pytorch-image-models` (timm) library and the decoders are basically re-implementations of the decoders in CellPose and other models.

**Comment by vadori** [comment]
Hi @,

**Comment by okunator** [comment]
Hi again,

I haven't made any diagrams but basically the encoder class follows the UNET-TR logic. [https://arxiv.org/pdf/2103.10504](https://arxiv.org/pdf/2103.10504)

**Comment by vadori** [comment]
Great, thanks for sharing the reference!
